version: "3"
volumes:
  db-store:
services:
  mvn:
    env_file: ./.env
    tty: true
    ports:
      - 3000:8080
    volumes:
      - type: bind
        source: ./backend/${HOST_BACKEND_SRC_PATH:-src/spring-boot-demo}
        target: "/work/maven"
    build:
      context: ./backend
      dockerfile: ./mvn/Dockerfile
      args:
        HOST_BACKEND_SRC_PATH: ${HOST_BACKEND_SRC_PATH:-src/spring-boot-demo}
        OWNER_USER_ID: ${OWNER_USER_ID}
        OWNER_GROUP_ID: ${OWNER_USER_ID}
        DB_CONNECTION: mysql
  
  db:
    env_file: ./.env
    ports:
      - ${DB_EXT_PORT:-3306}:3306
    volumes:
      - db-store:/var/lib/mysql
    build:
      context: ./backend
      dockerfile: ./db/mysql/Dockerfile
    environment:
      - MYSQL_DATABASE=${DB_NAME:-spring_local}
      - MYSQL_USER=${DB_USER:-javarista}
      - MYSQL_PASSWORD=${DB_PASS:-secret}
      - MYSQL_ROOT_PASSWORD=${DB_PASS:-secret}
